# Generated by Django 5.0 on 2024-02-22 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_securevault', '0002_digitaldocuments_educationaldetails_financialdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DigitalDocuments',
        ),
    ]
