# Generated by Django 5.0 on 2024-03-04 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_securevault', '0003_delete_digitaldocuments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationaldetails',
            name='foreignkey',
        ),
        migrations.RemoveField(
            model_name='financialdetails',
            name='foreignkey',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='foreignkey',
        ),
        migrations.DeleteModel(
            name='Sign_up',
        ),
        migrations.DeleteModel(
            name='EducationalDetails',
        ),
        migrations.DeleteModel(
            name='FinancialDetails',
        ),
        migrations.DeleteModel(
            name='HealthRecord',
        ),
        migrations.DeleteModel(
            name='Sign_in',
        ),
    ]
